;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env4,@env12,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env8,@env16,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env9,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0e
	.word @env4,@env13,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env4,@env14,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env4,@env15,@env0
	.byte $00
	.byte $b0 ;instrument $1a
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $26
	.word @env11,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c1,$c2,$c3,$c5,$00,$03
@env2:
	.byte $c1,$c3,$c6,$ca,$00,$03
@env3:
	.byte $cf,$00,$00
@env4:
	.byte $c2,$c3,$c4,$02,$c3,$c3,$c2,$07,$c2,$00,$08
@env5:
	.byte $ca,$c9,$c7,$c4,$c2,$c0,$00,$05
@env6:
	.byte $cf,$cd,$cb,$c9,$c7,$c6,$c5,$c4,$c3,$06,$c3,$00,$0a
@env7:
	.byte $cd,$cb,$ca,$c9,$c8,$c7,$c7,$c6,$c4,$c3,$c2,$c2,$c1,$c4,$c4,$c3
	.byte $c2,$c2,$c1,$02,$c0,$0a,$c1,$c2,$c1,$06,$c0,$00,$1a
@env8:
	.byte $cd,$cb,$c9,$c7,$c5,$c4,$c2,$c1,$c0,$00,$08
@env9:
	.byte $ca,$c5,$c3,$c2,$c0,$00,$04
@env10:
	.byte $cb,$ca,$c8,$c7,$c4,$c3,$c2,$c1,$c0,$00,$08
@env11:
	.byte $c9,$07,$c6,$05,$c9,$07,$c9,$00,$06
@env12:
	.byte $c0,$c4,$c7,$cc,$00,$00
@env13:
	.byte $bb,$c0,$c3,$c7,$00,$00
@env14:
	.byte $c0,$c3,$c7,$ca,$00,$00
@env15:
	.byte $bb,$be,$c0,$c4,$00,$00
@env16:
	.byte $c7,$c3,$c0,$bd,$00,$02


@song0ch0:
	.byte $fb,$06
@ref0:
	.byte $00,$a5,$8e,$53,$53,$4b,$4b,$53,$52,$81
@ref1:
	.byte $4e,$a5,$4f,$4f,$49,$49,$53,$4e,$81
@song0ch0loop:
@ref2:
	.byte $9c,$4a,$a5,$53,$53,$4b,$4b,$53,$52,$81
	.byte $ff,$09
	.word @ref1
@ref4:
	.byte $4a,$9d,$9e,$24,$85,$8e,$55,$59,$5d,$59,$55,$58,$81
@ref5:
	.byte $54,$85,$52,$85,$84,$32,$95,$8e,$4f,$4f,$4f,$4f,$4b,$4e,$81
@ref6:
	.byte $52,$85,$84,$32,$95,$9e,$24,$85,$8e,$55,$59,$5d,$59,$55,$58,$81
@ref7:
	.byte $54,$85,$52,$85,$84,$32,$95,$8e,$4f,$4f,$4f,$4f,$4b,$48,$81
	.byte $ff,$09
	.word @ref2
	.byte $ff,$09
	.word @ref1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref10:
	.byte $00,$a5,$94,$41,$41,$3b,$3b,$41,$40,$81
@ref11:
	.byte $40,$85,$9e,$28,$85,$41,$01,$28,$85,$41,$01,$94,$41,$41,$37,$37
	.byte $41,$30,$81
@song0ch1loop:
@ref12:
	.byte $94,$3a,$85,$9e,$28,$85,$41,$01,$28,$85,$41,$01,$94,$41,$41,$3b
	.byte $3b,$41,$40,$81
@ref13:
	.byte $40,$85,$9e,$28,$85,$41,$01,$28,$85,$40,$85,$94,$41,$41,$37,$37
	.byte $41,$30,$81
@ref14:
	.byte $3a,$85,$9e,$28,$85,$41,$01,$28,$85,$84,$3c,$85,$94,$3d,$41,$45
	.byte $41,$45,$48,$81
@ref15:
	.byte $84,$32,$85,$9e,$28,$85,$3b,$29,$3b,$37,$84,$40,$85,$94,$4f,$4f
	.byte $41,$41,$4b,$40,$81
@ref16:
	.byte $84,$33,$9e,$3b,$3d,$41,$45,$33,$37,$3b,$84,$3c,$85,$94,$3d,$41
	.byte $45,$41,$45,$48,$81
@ref17:
	.byte $86,$32,$85,$9e,$28,$85,$3b,$29,$3b,$37,$84,$40,$85,$94,$4f,$4f
	.byte $41,$41,$4b,$40,$81
@ref18:
	.byte $3a,$85,$9e,$28,$85,$41,$01,$28,$85,$41,$01,$94,$41,$41,$3b,$3b
	.byte $41,$40,$81
	.byte $ff,$11
	.word @ref13
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref20:
	.byte $80,$32,$8d,$28,$8d,$33,$00,$99
@ref21:
	.byte $40,$8d,$36,$8d,$40,$8d,$36,$8d
@song0ch2loop:
	.byte $ff,$07
	.word @ref20
	.byte $ff,$08
	.word @ref21
@ref24:
	.byte $32,$8d,$28,$8d,$24,$85,$1a,$85,$14,$85,$24,$85
@ref25:
	.byte $28,$85,$22,$85,$1a,$85,$28,$85,$28,$85,$1e,$85,$18,$85,$28,$85
@ref26:
	.byte $28,$85,$22,$85,$1a,$85,$28,$85,$24,$85,$1a,$85,$14,$85,$24,$85
	.byte $ff,$10
	.word @ref25
@ref28:
	.byte $32,$8d,$28,$8d,$33,$00,$99
	.byte $ff,$08
	.word @ref21
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref30:
	.byte $8a,$02,$85,$88,$0d,$17,$8a,$02,$85,$88,$0c,$85,$8a,$02,$85,$88
	.byte $0d,$13,$8a,$02,$85,$88,$0c,$85
@ref31:
	.byte $8a,$02,$85,$88,$0d,$17,$8a,$02,$85,$88,$0c,$85,$8a,$02,$85,$88
	.byte $0d,$17,$8a,$02,$85,$88,$0c,$85
@song0ch3loop:
	.byte $ff,$10
	.word @ref30
	.byte $ff,$10
	.word @ref31
	.byte $ff,$10
	.word @ref30
	.byte $ff,$10
	.word @ref31
	.byte $ff,$10
	.word @ref30
	.byte $ff,$10
	.word @ref31
	.byte $ff,$10
	.word @ref30
	.byte $ff,$10
	.word @ref31
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref40:
	.byte $bf
@ref41:
	.byte $bf
@song0ch4loop:
@ref42:
	.byte $bf
@ref43:
	.byte $bf
@ref44:
	.byte $bf
@ref45:
	.byte $bf
@ref46:
	.byte $bf
@ref47:
	.byte $bf
@ref48:
	.byte $bf
@ref49:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref50:
	.byte $90,$5d,$5d,$5d,$57,$5b,$5b,$5b,$57,$5d,$5d,$5d,$57,$5b,$5b,$5a
	.byte $85,$56,$85,$56,$85,$56,$8d
@ref51:
	.byte $58,$83,$52,$83,$4f,$4c,$83,$4e,$83,$53,$56,$8d,$56,$8d
@ref52:
	.byte $57,$4f,$49,$4f,$65,$5d,$5c,$85,$57,$4f,$49,$4f,$65,$5d,$5c,$85
@ref53:
	.byte $61,$60,$60,$5d,$61,$57,$57,$56,$85,$61,$60,$60,$5d,$61,$57,$57
	.byte $56,$85
@ref54:
	.byte $52,$89,$53,$53,$59,$57,$53,$57,$4e,$99
	.byte $ff,$0a
	.word @ref54
	.byte $ff,$12
	.word @ref53
@ref57:
	.byte $4c,$8d,$52,$8d
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref58:
	.byte $92,$4f,$4f,$4f,$57,$49,$49,$49,$45,$4f,$4f,$4f,$57,$49,$49,$49
	.byte $45,$36,$85,$48,$85,$36,$8d
@ref59:
	.byte $36,$83,$40,$37,$31,$44,$89,$41,$36,$8d,$4e,$8d
@ref60:
	.byte $82,$48,$00,$48,$00,$48,$00,$48,$00,$56,$00,$56,$00,$52,$00,$53
	.byte $48,$00,$48,$00,$48,$00,$48,$00,$56,$00,$56,$00,$52,$00,$52,$81
@ref61:
	.byte $56,$00,$56,$00,$52,$00,$57,$4e,$00,$36,$00,$36,$85,$56,$00,$56
	.byte $00,$52,$00,$57,$4e,$00,$36,$00,$36,$85
@ref62:
	.byte $22,$8d,$1a,$85,$14,$85,$18,$9d
	.byte $ff,$08
	.word @ref62
	.byte $ff,$1a
	.word @ref61
@ref65:
	.byte $0b,$00,$89,$15,$00,$89
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref66:
	.byte $80,$1f,$01,$27,$2d,$00,$89,$15,$1f,$01,$27,$2d,$00,$89,$15,$3e
	.byte $00,$3a,$36,$3e,$00,$3a,$36,$3f,$01,$31,$00,$81
@ref67:
	.byte $29,$00,$30,$37,$01,$2c,$83,$34,$01,$41,$36,$83,$00,$87,$47,$00
	.byte $89
@ref68:
	.byte $90,$19,$01,$27,$31,$2c,$85,$01,$0f,$19,$01,$27,$31,$2c,$85,$01
	.byte $0e,$81
@ref69:
	.byte $80,$18,$85,$30,$85,$27,$1f,$19,$01,$18,$85,$30,$85,$27,$1f,$19
	.byte $00,$81
@ref70:
	.byte $1a,$83,$00,$23,$32,$85,$00,$89,$18,$83,$00,$27,$31,$18,$83,$00
	.byte $27,$30,$81
	.byte $ff,$13
	.word @ref70
@ref72:
	.byte $18,$85,$30,$85,$27,$1f,$19,$01,$18,$85,$30,$85,$27,$1f,$19,$00
	.byte $81
@ref73:
	.byte $14,$00,$8b,$1c,$00,$8b
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref74:
	.byte $8a,$03,$03,$8c,$15,$88,$0e,$8d,$14,$18,$8a,$03,$03,$8c,$15,$88
	.byte $0e,$8f,$14,$18,$85,$14,$85,$15,$8c,$1f,$1f,$1e,$81
@ref75:
	.byte $8a,$02,$83,$88,$10,$83,$8a,$03,$88,$12,$83,$10,$83,$8a,$21,$20
	.byte $8b,$20,$12,$8d
@ref76:
	.byte $8c,$20,$83,$20,$88,$02,$85,$8c,$21,$21,$88,$02,$85,$8c,$20,$83
	.byte $20,$88,$02,$85,$8c,$21,$21,$88,$02,$85
	.byte $ff,$12
	.word @ref76
	.byte $ff,$12
	.word @ref76
	.byte $ff,$12
	.word @ref76
	.byte $ff,$12
	.word @ref76
	.byte $ff,$09
	.word @ref76
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref82:
	.byte $df
@ref83:
	.byte $bf
@ref84:
	.byte $bf
@ref85:
	.byte $bf
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref90:
	.byte $86,$4e,$89,$58,$85,$01,$4e,$85
@ref91:
	.byte $52,$89,$5c,$85,$00,$85,$58,$81
@ref92:
	.byte $56,$00,$56,$00,$56,$00,$56,$00,$56,$00,$56,$00,$52,$00,$56,$00
@ref93:
	.byte $83,$5d,$01,$59,$4f,$01,$53,$00,$81
@ref94:
	.byte $4e,$89,$58,$85,$01,$4e,$85
	.byte $ff,$08
	.word @ref91
	.byte $ff,$10
	.word @ref92
@ref97:
	.byte $83,$5d,$01,$59,$59,$01,$5d,$00,$81
@ref98:
	.byte $90,$49,$49,$49,$3f,$49,$49,$45,$40,$85,$48,$85,$40,$85,$3a,$85
	.byte $3e,$81
@ref99:
	.byte $83,$48,$85,$39,$3f,$3b,$39,$3a,$85,$30,$99
@ref100:
	.byte $49,$49,$49,$3f,$49,$49,$45,$40,$85,$44,$85,$48,$85,$4a,$89
@ref101:
	.byte $82,$4a,$8d,$90,$4f,$4b,$41,$44,$85,$00,$8d,$82,$36,$85,$00,$81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref102:
	.byte $94,$30,$89,$36,$89,$30,$85
@ref103:
	.byte $32,$89,$3a,$91
@ref104:
	.byte $36,$9b,$00
@ref105:
	.byte $83,$41,$01,$37,$31,$01,$33,$00,$81
@ref106:
	.byte $30,$89,$36,$89,$30,$85
@ref107:
	.byte $32,$89,$3a,$91
@ref108:
	.byte $36,$9b,$00
@ref109:
	.byte $83,$41,$01,$37,$41,$00,$85,$00,$81
@ref110:
	.byte $30,$89,$38,$89,$30,$85,$3a,$89,$40,$89,$3a,$85
@ref111:
	.byte $30,$89,$3e,$89,$30,$85,$3a,$89,$40,$85,$00,$89
@ref112:
	.byte $30,$89,$3e,$89,$38,$85,$3a,$89,$40,$85,$3a,$89
@ref113:
	.byte $40,$99,$82,$36,$91,$01,$46,$85,$00,$81
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref114:
	.byte $80,$29,$01,$30,$34,$37,$01,$30,$00,$28,$00,$22,$00
@ref115:
	.byte $2d,$00,$38,$3b,$35,$00,$89,$32,$81
@ref116:
	.byte $1f,$01,$27,$2d,$01,$27,$1f,$26,$00
@ref117:
	.byte $83,$2d,$01,$29,$27,$01,$22,$85
@ref118:
	.byte $29,$01,$30,$34,$37,$01,$30,$00,$28,$00,$22,$00
	.byte $ff,$09
	.word @ref115
	.byte $ff,$09
	.word @ref116
@ref121:
	.byte $83,$2d,$01,$28,$00,$29,$01,$82,$37,$00,$81
@ref122:
	.byte $80,$30,$85,$01,$21,$01,$27,$21,$23,$01,$29,$01,$31,$01,$29,$23
	.byte $28,$81
@ref123:
	.byte $26,$85,$01,$30,$85,$01,$21,$01,$3b,$31,$01,$37,$01,$33,$2d,$00
	.byte $81
@ref124:
	.byte $30,$85,$01,$21,$01,$27,$21,$23,$01,$29,$01,$31,$01,$29,$23,$28
	.byte $81
@ref125:
	.byte $1b,$01,$23,$29,$01,$23,$1b,$01,$1f,$01,$27,$2d,$01,$2e,$89
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref126:
	.byte $8a,$02,$85,$88,$19,$8a,$02,$85,$88,$0d,$0d,$0c,$81
@ref127:
	.byte $8a,$02,$85,$88,$19,$8a,$02,$85,$88,$0d,$18,$85
@ref128:
	.byte $8a,$20,$85,$88,$18,$85,$8a,$20,$85,$88,$19,$18,$81
@ref129:
	.byte $83,$18,$85,$0b,$0a,$85,$20,$85
	.byte $ff,$09
	.word @ref126
	.byte $ff,$08
	.word @ref127
	.byte $ff,$09
	.word @ref128
	.byte $ff,$08
	.word @ref129
@ref134:
	.byte $8a,$20,$85,$88,$18,$85,$8a,$20,$85,$88,$19,$8a,$20,$85,$88,$18
	.byte $85,$18,$85,$19,$18,$85
	.byte $ff,$10
	.word @ref134
	.byte $ff,$10
	.word @ref134
	.byte $ff,$10
	.word @ref134
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref138:
	.byte $9f
@ref139:
	.byte $9f
@ref140:
	.byte $9f
@ref141:
	.byte $9f
@ref142:
	.byte $9f
@ref143:
	.byte $9f
@ref144:
	.byte $9f
@ref145:
	.byte $9f
@ref146:
	.byte $bf
@ref147:
	.byte $bf
@ref148:
	.byte $bf
@ref149:
	.byte $bf
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref150:
	.byte $90,$52,$85,$52,$85,$52,$85,$55,$58,$85,$62,$87,$00,$8f
@ref151:
	.byte $52,$85,$52,$85,$52,$85,$4f,$52,$a1
@ref152:
	.byte $52,$85,$52,$85,$52,$85,$55,$58,$85,$62,$89,$62,$85,$66,$85
@ref153:
	.byte $6a,$8d,$6a,$85,$67,$62,$a1
@ref154:
	.byte $5d,$5d,$5d,$5d,$62,$85,$62,$8d,$82,$67,$01,$62,$85,$00,$85
@ref155:
	.byte $90,$59,$59,$59,$59,$62,$85,$62,$8d,$82,$67,$01,$62,$85,$00,$85
@ref156:
	.byte $90,$4f,$4f,$4f,$4f,$54,$85,$54,$8d,$5c,$85,$59,$59,$54,$85
@ref157:
	.byte $52,$85,$55,$58,$91,$82,$63,$01,$61,$01,$5c,$85,$59,$00,$81
@ref158:
	.byte $90,$5d,$5d,$5d,$5d,$62,$85,$62,$8d,$82,$67,$01,$62,$85,$00,$85
	.byte $ff,$0e
	.word @ref155
	.byte $ff,$0e
	.word @ref156
@ref161:
	.byte $52,$85,$62,$95,$82,$33,$3d,$45,$4b,$49,$41,$37,$00,$81
@ref162:
	.byte $90,$6a,$85,$66,$85,$62,$85,$6b,$66,$85,$60,$89,$6a,$85,$66,$85
@ref163:
	.byte $62,$85,$61,$5c,$85,$62,$95,$5d,$61,$5d,$61,$58,$81
@ref164:
	.byte $ab,$59,$5d,$59,$5d,$54,$81
@ref165:
	.byte $ab,$55,$59,$55,$58,$85
@ref166:
	.byte $52,$85,$62,$95
@ref167:
	.byte $82,$33,$3d,$45,$4b,$49,$41,$37,$00,$81
	.byte $ff,$0f
	.word @ref162
@ref169:
	.byte $62,$85,$61,$5c,$85,$62,$95,$5d,$61,$5d,$60,$85
@ref170:
	.byte $58,$85,$62,$95
@ref171:
	.byte $8b,$5d,$61,$5d,$60,$85
@ref172:
	.byte $62,$85,$62,$95
	.byte $ff,$09
	.word @ref167
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref174:
	.byte $94,$41,$01,$41,$01,$41,$01,$4b,$53,$01,$4b,$00,$95
@ref175:
	.byte $41,$01,$41,$01,$41,$01,$45,$40,$00,$97,$84,$4b,$00,$81
	.byte $ff,$0c
	.word @ref174
	.byte $ff,$0d
	.word @ref175
@ref178:
	.byte $54,$85,$01,$55,$3d,$54,$85,$01,$54,$85,$01,$3d,$54,$85,$00,$85
@ref179:
	.byte $4a,$85,$01,$4b,$33,$4a,$85,$01,$4a,$85,$01,$33,$4a,$85,$00,$85
@ref180:
	.byte $98,$4e,$85,$01,$4f,$37,$4e,$85,$01,$9a,$58,$85,$01,$41,$58,$85
	.byte $00,$85
@ref181:
	.byte $84,$4a,$85,$01,$4b,$33,$4a,$85,$01,$4a,$85,$01,$33,$4a,$85,$00
	.byte $85
	.byte $ff,$10
	.word @ref178
	.byte $ff,$10
	.word @ref179
	.byte $ff,$10
	.word @ref180
@ref185:
	.byte $84,$4a,$85,$01,$4b,$33,$4a,$85,$01,$98,$4f,$01,$4f,$37,$9a,$59
	.byte $41,$59,$00,$81
@ref186:
	.byte $84,$32,$85,$01,$4b,$32,$85,$01,$96,$3a,$00,$3a,$85,$01,$53,$3a
	.byte $85,$01,$52,$81
@ref187:
	.byte $98,$44,$85,$01,$5d,$44,$85,$01,$5d,$84,$3c,$85,$01,$55,$3c,$85
	.byte $01,$4a,$81
@ref188:
	.byte $4a,$85,$01,$4b,$33,$4a,$85,$01,$4a,$85,$01,$4b,$33,$4a,$85,$00
	.byte $81
	.byte $ff,$10
	.word @ref180
@ref190:
	.byte $84,$4a,$85,$01,$4b,$33,$4a,$85,$00,$81
@ref191:
	.byte $98,$4f,$01,$4f,$37,$9a,$59,$41,$59,$00,$81
	.byte $ff,$12
	.word @ref186
	.byte $ff,$11
	.word @ref187
@ref194:
	.byte $4a,$85,$01,$4b,$33,$4a,$85,$00,$81
	.byte $ff,$09
	.word @ref191
	.byte $ff,$09
	.word @ref190
	.byte $ff,$09
	.word @ref191
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref198:
	.byte $80,$1a,$85,$01,$1a,$00,$1a,$85,$01,$29,$1a,$85,$01,$1a,$00,$1b
	.byte $33,$29,$22,$81
@ref199:
	.byte $1a,$85,$01,$1a,$00,$1a,$85,$01,$29,$1a,$85,$01,$1a,$00,$1a,$85
	.byte $28,$22,$1a,$81
@ref200:
	.byte $1a,$85,$01,$1a,$00,$1a,$85,$01,$29,$1a,$85,$01,$1a,$00,$1b,$33
	.byte $29,$22,$81
	.byte $ff,$14
	.word @ref199
@ref202:
	.byte $24,$85,$01,$1b,$25,$2d,$25,$00,$89,$1b,$01,$24,$85,$00,$85
@ref203:
	.byte $22,$85,$01,$1b,$23,$29,$22,$85,$00,$85,$1b,$01,$22,$85,$00,$85
@ref204:
	.byte $1e,$85,$01,$25,$2d,$32,$85,$01,$1e,$85,$01,$25,$29,$31,$00,$85
@ref205:
	.byte $1a,$85,$01,$23,$1b,$10,$85,$01,$23,$01,$29,$01,$33,$01,$28,$85
	.byte $ff,$0f
	.word @ref202
	.byte $ff,$10
	.word @ref203
	.byte $ff,$10
	.word @ref204
@ref209:
	.byte $1a,$85,$01,$23,$1b,$10,$85,$01,$82,$24,$00,$24,$00,$24,$00,$24
	.byte $00,$28,$00,$28,$00,$28,$2c,$30,$32
@ref210:
	.byte $80,$1a,$85,$01,$1a,$00,$1a,$85,$01,$18,$00,$18,$85,$01,$18,$00
	.byte $18,$85,$01,$18,$00
@ref211:
	.byte $14,$85,$01,$14,$00,$14,$85,$01,$14,$00,$14,$85,$01,$1b,$24,$85
	.byte $01,$1a,$81
@ref212:
	.byte $1a,$85,$01,$23,$1b,$10,$85,$01,$1a,$85,$01,$23,$1b,$10,$85,$00
	.byte $81
	.byte $ff,$10
	.word @ref204
@ref214:
	.byte $1a,$85,$01,$23,$1b,$10,$85,$00,$81
@ref215:
	.byte $82,$24,$00,$24,$00,$24,$00,$24,$00,$28,$00,$28,$00,$28,$2c,$30
	.byte $32
	.byte $ff,$14
	.word @ref210
	.byte $ff,$13
	.word @ref211
	.byte $ff,$09
	.word @ref214
@ref219:
	.byte $24,$85,$01,$1f,$28,$89,$00,$81
	.byte $ff,$09
	.word @ref214
	.byte $ff,$10
	.word @ref215
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref222:
	.byte $8a,$20,$85,$88,$13,$8a,$21,$20,$85,$88,$12,$85,$8a,$20,$85,$88
	.byte $13,$8a,$21,$20,$85,$88,$13,$12,$81
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$08
	.word @ref222
@ref239:
	.byte $8a,$20,$85,$88,$13,$8a,$21,$20,$85,$88,$13,$12,$81
	.byte $ff,$11
	.word @ref222
	.byte $ff,$11
	.word @ref222
	.byte $ff,$08
	.word @ref222
	.byte $ff,$09
	.word @ref239
	.byte $ff,$08
	.word @ref222
	.byte $ff,$09
	.word @ref239
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref246:
	.byte $bf
@ref247:
	.byte $bf
@ref248:
	.byte $bf
@ref249:
	.byte $bf
@ref250:
	.byte $bf
@ref251:
	.byte $bf
@ref252:
	.byte $bf
@ref253:
	.byte $bf
@ref254:
	.byte $bf
@ref255:
	.byte $bf
@ref256:
	.byte $bf
@ref257:
	.byte $bf
@ref258:
	.byte $bf
@ref259:
	.byte $bf
@ref260:
	.byte $bf
@ref261:
	.byte $bf
@ref262:
	.byte $9f
@ref263:
	.byte $9f
@ref264:
	.byte $bf
@ref265:
	.byte $bf
@ref266:
	.byte $9f
@ref267:
	.byte $9f
@ref268:
	.byte $9f
@ref269:
	.byte $9f
	.byte $fd
	.word @song3ch4loop
