// ..\dev\assets\enems9.h
// Generated by eneexpp.exe v0.1 [20170531]
// Copyleft 2017 The Mojon Twins

// YYYYYYYY XXXXTTTT BBBBAAAA
// enems stored in decreasing Y order

const unsigned char enems_strip_9 [] = {
	69, 0x77, 0xb7,
	66, 0x87, 0x48,
	63, 0x47, 0xb4,
	60, 0x27, 0xd2,
	54, 0x87, 0xc8,
	51, 0x87, 0x48,
	25, 0x62, 0x02,
	22, 0xa2, 0x12,
	6, 0x71, 0x00,
	0, 0, 0 // end marker
};

