// ..\dev\assets\enems8.h
// Generated by eneexpp.exe v0.1 [20170531]
// Copyleft 2017 The Mojon Twins

// YYYYYYYY XXXXTTTT BBBBAAAA
// enems stored in decreasing Y order

const unsigned char enems_strip_8 [] = {
	56, 0x42, 0x01,
	53, 0xe2, 0x11,
	50, 0x62, 0x01,
	16, 0x33, 0x02,
	16, 0xc3, 0x12,
	0, 0, 0 // end marker
};

